apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - service.yaml
  - deployment.yaml
helmCharts:
  - name: postgresql
    releaseName: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 12.1.6
    namespace: production
    valuesFile: postgresql-values.yaml
